AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  combine-pdf

  Sample SAM Template for combine-pdf

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  CombinePdfFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: combine_pdf/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        CombinePdf:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /combine
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CombinePdfApi:
    Description: "API Gateway endpoint URL for Prod stage for Combine PDF function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/combine/"
  CombinePdfFunction:
    Description: "Combine PDF Lambda Function ARN"
    Value: !GetAtt CombinePdfFunction.Arn
  CombinePdfFunctionIamRole:
    Description: "Implicit IAM Role created for Combine PDF function"
    Value: !GetAtt CombinePdfFunctionRole.Arn
